# -*- coding: utf-8 -*-
"""seguros.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KIreRqck0hmNJzyb-OIldqJhdIsGR37i
"""

!pip install sqlalchemy psycopg2-binary

import pandas as pd
import numpy as np
from sqlalchemy import create_engine
import os

# Configuración de la nueva base de datos en Render
DB_URL = "postgresql://etldb_9y9z_user:GKHKpR6jtYEN2XkaSoLJjnuxajSBKPpQ@dpg-d6vm5qv5gffc73ddhbn0-a.oregon-postgres.render.com/etldb_9y9z"
engine = create_engine(DB_URL)

print("✅ Librerías cargadas y motor de base de datos listo.")

# =========================================================
# PIPELINE ETL: SISTEMA DE SEGUROS (6 TABLAS)
# =========================================================

import pandas as pd
import numpy as np
from sqlalchemy import create_engine
import os

# --- 1. CONFIGURACIÓN DE CONEXIÓN Y RUTAS ---
DB_URL = "postgresql://etldb_9y9z_user:GKHKpR6jtYEN2XkaSoLJjnuxajSBKPpQ@dpg-d6vm5qv5gffc73ddhbn0-a.oregon-postgres.render.com/etldb_9y9z"
engine = create_engine(DB_URL)

urls = {
    "aseguradoras": "https://raw.githubusercontent.com/2521812022/etl/refs/heads/main/data/raw/aseguradoras.csv",
    "clientes": "https://raw.githubusercontent.com/2521812022/etl/refs/heads/main/data/raw/clientes.csv",
    "corredores": "https://raw.githubusercontent.com/2521812022/etl/refs/heads/main/data/raw/corredores.csv",
    "polizas": "https://raw.githubusercontent.com/2521812022/etl/refs/heads/main/data/raw/polizas.csv",
    "siniestros": "https://raw.githubusercontent.com/2521812022/etl/refs/heads/main/data/raw/siniestros.csv",
    "tipos_seguro": "https://raw.githubusercontent.com/2521812022/etl/refs/heads/main/data/raw/tipos_seguro.csv"
}

# --- 2. EXTRACCIÓN (LOAD) ---
print("📥 Cargando datos desde GitHub...")
aseguradoras = pd.read_csv(urls["aseguradoras"])
clientes = pd.read_csv(urls["clientes"])
corredores = pd.read_csv(urls["corredores"])
polizas = pd.read_csv(urls["polizas"])
siniestros = pd.read_csv(urls["siniestros"])
tipos_seguro = pd.read_csv(urls["tipos_seguro"])

# --- 3. FUNCIONES DE TRANSFORMACIÓN ---
def normalizar_y_limpiar(df):
    # Columnas a minúsculas y sin espacios
    df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_", regex=False)
    # Quitar duplicados
    df = df.drop_duplicates()
    # Limpiar textos y nulos
    for col in df.select_dtypes(include='object').columns:
        df[col] = df[col].astype(str).str.strip()
        df[col] = df[col].replace(['nan', 'None', 'NULL', 'null', '', '-'], pd.NA)
    return df

def limpiar_monto_pro(serie):
    # Quita $, comas y espacios, luego convierte a número
    serie_limpia = serie.astype(str).str.replace(r'[\$, ]', '', regex=True)
    return pd.to_numeric(serie_limpia, errors='coerce')

# Aplicar limpieza básica inicial
dfs = [aseguradoras, clientes, corredores, polizas, siniestros, tipos_seguro]
aseguradoras, clientes, corredores, polizas, siniestros, tipos_seguro = [normalizar_y_limpiar(df) for df in dfs]

# --- 4. TRANSFORMACIONES DE NEGOCIO (FECHAS Y MONTOS) ---
print("⚙️ Aplicando transformaciones de negocio...")

# Clientes
clientes['fecha_nacimiento'] = pd.to_datetime(clientes['fecha_nacimiento'], errors='coerce')

# Pólizas
polizas['fecha_emision'] = pd.to_datetime(polizas['fecha_emision'], errors='coerce')
polizas['prima'] = limpiar_monto_pro(polizas['prima'])
polizas['comision'] = limpiar_monto_pro(polizas['comision'])
polizas['monto_asegurado'] = limpiar_monto_pro(polizas['monto_asegurado'])

# Siniestros
siniestros['fecha_siniestro'] = pd.to_datetime(siniestros['fecha_siniestro'], errors='coerce')
siniestros['monto_siniestro'] = limpiar_monto_pro(siniestros['monto_siniestro'])

# Corredores
corredores['anios_experiencia'] = pd.to_numeric(corredores['anios_experiencia'], errors='coerce')

# Tipos de Seguro
tipos_seguro['riesgo_base'] = limpiar_monto_pro(tipos_seguro['riesgo_base'])

# --- 5. VALIDACIÓN Y SEPARACIÓN (CURATED VS REJECTS) ---
print("🔍 Validando calidad de datos...")

# Clientes
c_curated = clientes[clientes['nombre'].notna() & clientes['email'].notna()].copy()
c_rejects = clientes[clientes['nombre'].isna() | clientes['email'].isna()].copy()
c_rejects['motivo_rechazo'] = "nombre_o_email_vacio"

# Pólizas
p_curated = polizas[polizas['fecha_emision'].notna() & (polizas['prima'] > 0)].copy()
p_rejects = polizas[polizas['fecha_emision'].isna() | (polizas['prima'] <= 0) | polizas['prima'].isna()].copy()
p_rejects['motivo_rechazo'] = "fecha_invalida_o_prima_vacia"

# Siniestros
s_curated = siniestros[siniestros['fecha_siniestro'].notna() & (siniestros['monto_siniestro'] > 0)].copy()
s_rejects = siniestros[siniestros['fecha_siniestro'].isna() | (siniestros['monto_siniestro'] <= 0) | siniestros['monto_siniestro'].isna()].copy()
s_rejects['motivo_rechazo'] = "siniestro_invalido"

# Aseguradoras
a_curated = aseguradoras[aseguradoras['nombre'].notna() & aseguradoras['pais'].notna()].copy()
a_rejects = aseguradoras[aseguradoras['nombre'].isna() | aseguradoras['pais'].isna()].copy()
a_rejects['motivo_rechazo'] = "datos_maestros_incompletos"

# Corredores
co_curated = corredores[corredores['nombre'].notna() & (corredores['anios_experiencia'] >= 0)].copy()
co_rejects = corredores[corredores['nombre'].isna() | corredores['anios_experiencia'].isna()].copy()
co_rejects['motivo_rechazo'] = "nombre_o_experiencia_invalida"

# Tipos de Seguro
t_curated = tipos_seguro[tipos_seguro['tipo'].notna()].copy()
t_rejects = tipos_seguro[tipos_seguro['tipo'].isna()].copy()
t_rejects['motivo_rechazo'] = "tipo_vacio"

# --- 6. EXPORTACIÓN A CSV Y CARGA A POSTGRES ---
print("📤 Exportando archivos y cargando a la base de datos...")

# Listas para automatizar
tablas_finales = {
    "clientes": c_curated, "polizas": p_curated, "siniestros": s_curated,
    "aseguradoras": a_curated, "corredores": co_curated, "tipos_seguro": t_curated
}
rechazos_finales = {
    "clientes": c_rejects, "polizas": p_rejects, "siniestros": s_rejects,
    "aseguradoras": a_rejects, "corredores": co_rejects, "tipos_seguro": t_rejects
}

# Borrar archivos viejos para evitar confusión
import os
for f in os.listdir():
    if f.endswith(".csv"): os.remove(f)

# Guardar Curated y cargar a SQL
for nombre, df in tablas_finales.items():
    df.to_csv(f"{nombre}_curated.csv", index=False)
    df.to_sql(nombre, engine, if_exists='replace', index=False)

# Guardar Rejects
for nombre, df in rechazos_finales.items():
    df.to_csv(f"{nombre}_rejects.csv", index=False)

print("\n🚀 ¡PROCESO FINALIZADO EXITOSAMENTE!")
print(f"Tablas cargadas en Render: {list(tablas_finales.keys())}")